<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:annotation>
    <xs:documentation>Schema module with the definition of the generate element.</xs:documentation>
  </xs:annotation>
  <xs:group name="g-generate">
    <xs:annotation>
      <xs:documentation>Macro definitions</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="generate">
        <xs:complexType>
          <xs:sequence>
            <xs:any maxOccurs="unbounded" minOccurs="0" namespace="##any" processContents="skip"/>
          </xs:sequence>
          <xs:attribute name="href-generator" type="xs:anyURI" use="required">
            <xs:annotation>
              <xs:documentation>The generator URI. Must be either an .xsl or .xpl document.</xs:documentation>
            </xs:annotation>
          </xs:attribute>
          <xs:anyAttribute namespace="##any" processContents="skip"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:group>
</xs:schema>
